/**
 * Audit Report Export Utilities
 * Handles Markdown and PDF export for Design Audit reports
 */

interface FrictionPoint {
  id: number;
  x: number;
  y: number;
  title: string;
  description: string;
  severity: "high" | "medium" | "low";
}

interface Persona {
  name: string;
  description?: string;
  pain_points?: string[];
  goals?: string[];
  demographics?: Record<string, any>;
}

interface ReportData {
  frictionPoints: FrictionPoint[];
  monologue: string;
  personaName: string;
  persona?: Persona;
  imageUrl?: string;
}

/**
 * Download content as a file
 */
function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Generate a basic Markdown report (client-side fallback)
 */
export function generateBasicMarkdownReport(data: ReportData): string {
  const timestamp = new Date().toLocaleString();
  
  const frictionPointsSection = data.frictionPoints.map((fp) => `
### Finding #${fp.id}: ${fp.title}

**Severity:** ${fp.severity.toUpperCase()}

**Location:** Approximately ${fp.x}% from left, ${fp.y}% from top

**Description:** ${fp.description}

---`).join('\n');

  return `# Usability Audit Report

*Generated: ${timestamp}*

## Executive Summary

This usability audit was conducted by simulating the experience of **${data.personaName}** interacting with the interface. The analysis identified **${data.frictionPoints.length} friction points** that may negatively impact the user experience for this persona type.

### Key Statistics
- **Persona Tested:** ${data.personaName}
- **Total Issues Found:** ${data.frictionPoints.length}
- **High Severity:** ${data.frictionPoints.filter(fp => fp.severity === 'high').length}
- **Medium Severity:** ${data.frictionPoints.filter(fp => fp.severity === 'medium').length}
- **Low Severity:** ${data.frictionPoints.filter(fp => fp.severity === 'low').length}

## Persona Profile

### ${data.personaName}

${data.persona?.description || 'A representative user persona used to evaluate the interface.'}

${data.persona?.pain_points?.length ? `**Pain Points:**\n${data.persona.pain_points.map(p => `- ${p}`).join('\n')}` : ''}

${data.persona?.goals?.length ? `**Goals:**\n${data.persona.goals.map(g => `- ${g}`).join('\n')}` : ''}

## Persona Monologue

> "${data.monologue}"

## Visual Heatmap Analysis

The following friction points were identified on the interface:

| # | Location | Severity | Issue |
|---|----------|----------|-------|
${data.frictionPoints.map(fp => `| ${fp.id} | (${fp.x}%, ${fp.y}%) | ${fp.severity} | ${fp.title} |`).join('\n')}

## Detailed Findings & Recommendations

${frictionPointsSection}

## Summary of Recommendations

${data.frictionPoints.map((fp, i) => `${i + 1}. **[${fp.severity.toUpperCase()}]** Address "${fp.title}" - ${fp.description.substring(0, 100)}...`).join('\n')}

## Conclusion

This audit identified ${data.frictionPoints.length} usability issues that should be addressed to improve the experience for users like ${data.personaName}. Priority should be given to high-severity issues that significantly impact task completion.

---

*Report generated by UX Probe - Automated Usability Analysis*
`;
}

/**
 * Download Markdown report
 */
export function downloadMarkdownReport(content: string, personaName: string) {
  const sanitizedName = personaName.replace(/[^a-zA-Z0-9]/g, '_');
  const filename = `UX_Audit_${sanitizedName}_${Date.now()}.md`;
  downloadFile(content, filename, 'text/markdown');
}

/**
 * Generate and download PDF report
 */
export function downloadPDFReport(content: string, personaName: string, imageUrl?: string) {
  const sanitizedName = personaName.replace(/[^a-zA-Z0-9]/g, '_');
  const filename = `UX_Audit_${sanitizedName}_${Date.now()}.html`;
  
  // Convert Markdown to HTML for PDF-like viewing
  const htmlContent = generatePDFHTML(content, imageUrl);
  downloadFile(htmlContent, filename, 'text/html');
}

/**
 * Generate HTML document that can be printed as PDF
 */
function generatePDFHTML(markdownContent: string, imageUrl?: string): string {
  // Basic Markdown to HTML conversion
  let htmlBody = markdownContent
    // Headers
    .replace(/^### (.+)$/gm, '<h3>$1</h3>')
    .replace(/^## (.+)$/gm, '<h2>$1</h2>')
    .replace(/^# (.+)$/gm, '<h1>$1</h1>')
    // Bold
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    // Italic
    .replace(/\*(.+?)\*/g, '<em>$1</em>')
    // Blockquotes
    .replace(/^> (.+)$/gm, '<blockquote>$1</blockquote>')
    // Horizontal rules
    .replace(/^---$/gm, '<hr>')
    // List items
    .replace(/^- (.+)$/gm, '<li>$1</li>')
    // Tables (basic)
    .replace(/\|(.+)\|/g, (match) => {
      const cells = match.split('|').filter(c => c.trim());
      if (cells.every(c => c.trim() === '---' || c.trim().match(/^-+$/))) {
        return '';
      }
      return '<tr>' + cells.map(c => `<td>${c.trim()}</td>`).join('') + '</tr>';
    })
    // Paragraphs (wrap lines not already wrapped)
    .split('\n').map(line => {
      if (line.match(/^<[^>]+>/) || line.trim() === '') return line;
      return `<p>${line}</p>`;
    }).join('\n');

  // Wrap list items in ul
  htmlBody = htmlBody.replace(/(<li>.+<\/li>\n?)+/g, '<ul>$&</ul>');
  
  // Wrap table rows in table
  htmlBody = htmlBody.replace(/(<tr>.+<\/tr>\n?)+/g, '<table>$&</table>');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>UX Audit Report</title>
  <style>
    @media print {
      body { margin: 0; }
      .page-break { page-break-before: always; }
    }
    
    * {
      box-sizing: border-box;
    }
    
    body {
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
      line-height: 1.6;
      color: #1a1a2e;
      max-width: 800px;
      margin: 0 auto;
      padding: 40px 20px;
      background: #fff;
    }
    
    h1 {
      color: #16213e;
      border-bottom: 3px solid #6366f1;
      padding-bottom: 10px;
      margin-top: 40px;
    }
    
    h2 {
      color: #16213e;
      border-bottom: 1px solid #e5e7eb;
      padding-bottom: 8px;
      margin-top: 30px;
    }
    
    h3 {
      color: #374151;
      margin-top: 20px;
    }
    
    blockquote {
      background: #f3f4f6;
      border-left: 4px solid #6366f1;
      margin: 20px 0;
      padding: 15px 20px;
      font-style: italic;
      color: #4b5563;
    }
    
    table {
      width: 100%;
      border-collapse: collapse;
      margin: 20px 0;
    }
    
    th, td {
      border: 1px solid #e5e7eb;
      padding: 10px 12px;
      text-align: left;
    }
    
    th {
      background: #f9fafb;
      font-weight: 600;
    }
    
    tr:nth-child(even) {
      background: #f9fafb;
    }
    
    ul {
      padding-left: 20px;
    }
    
    li {
      margin: 8px 0;
    }
    
    hr {
      border: none;
      border-top: 1px solid #e5e7eb;
      margin: 30px 0;
    }
    
    strong {
      color: #16213e;
    }
    
    .severity-high {
      color: #dc2626;
      font-weight: bold;
    }
    
    .severity-medium {
      color: #d97706;
      font-weight: bold;
    }
    
    .severity-low {
      color: #2563eb;
      font-weight: bold;
    }
    
    .mockup-image {
      max-width: 100%;
      border: 1px solid #e5e7eb;
      border-radius: 8px;
      margin: 20px 0;
    }
    
    .footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #e5e7eb;
      color: #6b7280;
      font-size: 0.875rem;
      text-align: center;
    }
  </style>
</head>
<body>
  ${imageUrl ? `<div class="page-break"><h2>Analyzed Mockup</h2><img src="${imageUrl}" alt="Analyzed mockup" class="mockup-image" /></div>` : ''}
  ${htmlBody}
  <div class="footer">
    <p>Generated by UX Probe - Automated Usability Analysis</p>
    <p>Print this page (Ctrl+P / Cmd+P) and select "Save as PDF" for a PDF version.</p>
  </div>
</body>
</html>`;
}
