import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

interface FrictionPoint {
  id: number;
  x: number;
  y: number;
  title: string;
  description: string;
  severity: "high" | "medium" | "low";
}

interface Persona {
  name: string;
  description?: string;
  painPoints?: string[];
  goals?: string[];
  demographics?: Record<string, any>;
}

interface ReportRequest {
  frictionPoints: FrictionPoint[];
  monologue: string;
  persona: Persona;
  imageUrl?: string;
}

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { frictionPoints, monologue, persona, imageUrl } = await req.json() as ReportRequest;

    if (!frictionPoints || !persona) {
      throw new Error("Friction points and persona are required");
    }

    const OPENAI_API_KEY = Deno.env.get("OPENAI_API_KEY");
    if (!OPENAI_API_KEY) {
      throw new Error("OpenAI API key not configured");
    }

    console.log(`Generating report for persona: ${persona.name}`);

    // Build context for AI
    const frustrations = persona.painPoints?.join(", ") || "general usability concerns";
    const goals = persona.goals?.join(", ") || "completing tasks efficiently";
    const description = persona.description || "a typical user";

    const findingsContext = frictionPoints.map((fp) => 
      `Issue #${fp.id} (${fp.severity} severity): "${fp.title}" - ${fp.description}`
    ).join("\n");

    const systemPrompt = `You are a professional UX Documentation Writer. Generate a structured usability audit report based on the simulation results.

PERSONA TESTED:
- Name: ${persona.name}
- Description: ${description}
- Frustrations: ${frustrations}
- Goals: ${goals}

SIMULATION MONOLOGUE:
"${monologue}"

FRICTION POINTS IDENTIFIED:
${findingsContext}

Generate a comprehensive report in the following Markdown format:

# Usability Audit Report

## Executive Summary
[Write a 2-3 paragraph executive summary highlighting the key findings, overall usability concerns, and immediate recommendations. Be specific about the impact on the target persona.]

## Persona Profile

### ${persona.name}
[Provide a brief but informative overview of the persona, their characteristics, goals, and pain points that are relevant to this audit.]

## Visual Heatmap Analysis
[Describe the visual analysis performed and the methodology. Note that ${frictionPoints.length} friction points were identified at specific locations on the interface.]

### Friction Point Locations
${frictionPoints.map(fp => `- **Point ${fp.id}** (${fp.severity}): Located at approximately ${fp.x}% from left, ${fp.y}% from top`).join('\n')}

## Detailed Findings & Recommendations

${frictionPoints.map(fp => `### Finding #${fp.id}: ${fp.title}

**Severity:** ${fp.severity.toUpperCase()}

**Issue Description:**
${fp.description}

**Recommendation:**
[Provide specific, actionable recommendations to address this issue based on UX best practices]

---`).join('\n\n')}

## Summary of Recommendations

[Provide a prioritized list of all recommendations, ordered by severity/impact]

## Conclusion

[Write a brief conclusion summarizing the audit and next steps]

---
*Report generated by UX Probe - Automated Usability Analysis*
`;

    const aiResponse = await fetch(
      "https://api.openai.com/v1/chat/completions",
      {
        method: "POST",
        headers: {
          "Authorization": `Bearer ${OPENAI_API_KEY}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          model: "gpt-4o-mini",
          messages: [
            {
              role: "user",
              content: systemPrompt,
            },
          ],
          max_tokens: 4096,
          temperature: 0.7,
        }),
      }
    );

    if (!aiResponse.ok) {
      const errorText = await aiResponse.text();
      console.error("OpenAI Error:", errorText);

      if (aiResponse.status === 429) {
        return new Response(
          JSON.stringify({ 
            success: false, 
            error: "Rate limit exceeded. Please try again in a moment." 
          }),
          { status: 429, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }
      if (aiResponse.status === 402) {
        return new Response(
          JSON.stringify({ 
            success: false, 
            error: "Payment required. Please check your OpenAI billing." 
          }),
          { status: 402, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      throw new Error(`AI report generation failed: ${aiResponse.status}`);
    }

    const aiData = await aiResponse.json();
    const reportContent = aiData.choices?.[0]?.message?.content || "";

    console.log("Report generated successfully");

    return new Response(
      JSON.stringify({
        success: true,
        report: reportContent,
        metadata: {
          personaName: persona.name,
          frictionPointCount: frictionPoints.length,
          generatedAt: new Date().toISOString(),
        },
      }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (error: any) {
    console.error("Error in generate-audit-report:", error);
    return new Response(
      JSON.stringify({ success: false, error: error.message }),
      { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
