figma.showUI(__html__, { width: 420, height: 680 });
figma.clientStorage.getAsync('uxprobe_session').then(function(s) { if (s) figma.ui.postMessage({ type: 'restore-session', session: s }); }).catch(function() {});
var THEMES = { wireframe: { primary: { r: 0.1, g: 0.1, b: 0.1 }, background: { r: 1, g: 1, b: 1 }, text: { r: 0.1, g: 0.1, b: 0.1 }, border: { r: 0.8, g: 0.8, b: 0.8 }, muted: { r: 0.6, g: 0.6, b: 0.6 } }, hifi: { primary: { r: 0.23, g: 0.51, b: 0.84 }, background: { r: 1, g: 1, b: 1 }, text: { r: 0.07, g: 0.09, b: 0.15 }, border: { r: 0.89, g: 0.91, b: 0.94 }, muted: { r: 0.45, g: 0.51, b: 0.6 } } };
function loadFonts() { return Promise.all([figma.loadFontAsync({ family: "Inter", style: "Bold" }), figma.loadFontAsync({ family: "Inter", style: "Regular" })]); }
function checkProto(nodes) { for (var i = 0; i < nodes.length; i++) { if (nodes[i].reactions && nodes[i].reactions.length) return true; if (nodes[i].children) for (var j = 0; j < nodes[i].children.length; j++) if (nodes[i].children[j].reactions && nodes[i].children[j].reactions.length) return true; } return false; }
function traverse(start) { var v = {}, f = [], q = [start]; while (q.length) { var c = q.shift(); if (!c || v[c.id]) continue; v[c.id] = true; f.push(c); if (c.reactions) for (var i = 0; i < c.reactions.length; i++) { var r = c.reactions[i]; if (r.action && r.action.destinationId) { var d = figma.getNodeById(r.action.destinationId); if (d && d.type === 'FRAME' && !v[d.id]) q.push(d); } } if (c.children) for (var j = 0; j < c.children.length; j++) { var ch = c.children[j]; if (ch.reactions) for (var k = 0; k < ch.reactions.length; k++) { var rr = ch.reactions[k]; if (rr.action && rr.action.destinationId) { var dd = figma.getNodeById(rr.action.destinationId); if (dd && dd.type === 'FRAME' && !v[dd.id]) q.push(dd); } } } } return f; }
figma.ui.onmessage = function(m) {
  if (m.type === 'store-session') figma.clientStorage.setAsync('uxprobe_session', m.session);
  else if (m.type === 'clear-session') figma.clientStorage.deleteAsync('uxprobe_session');
  else if (m.type === 'check-selection') { var s = figma.currentPage.selection, hf = s.some(function(n) { return n.type === 'FRAME'; }); figma.ui.postMessage({ type: 'selection-info', hasSelection: s.length > 0, hasFrame: hf, hasPrototypeLinks: hf && checkProto(s), selectedNodeName: s.length > 0 ? s[0].name : null }); }
  else if (m.type === 'run-audit') { var sel = figma.currentPage.selection, sf; for (var i = 0; i < sel.length; i++) if (sel[i].type === 'FRAME') { sf = sel[i]; break; } if (!sf) { figma.ui.postMessage({ type: 'audit-error', error: 'Select a frame' }); return; } figma.ui.postMessage({ type: 'audit-progress', progress: 10 }); var fr = m.mode === 'flow' ? traverse(sf) : [sf]; figma.ui.postMessage({ type: 'audit-status', message: 'Found ' + fr.length + ' frame(s)' }); var imgs = []; Promise.all(fr.map(function(f) { return f.exportAsync({ format: 'PNG', constraint: { type: 'SCALE', value: 1 } }).then(function(d) { imgs.push({ nodeId: f.id, name: f.name, imageData: 'data:image/png;base64,' + figma.base64Encode(d) }); }); })).then(function() { figma.ui.postMessage({ type: 'audit-progress', progress: 50 }); return fetch(m.apiUrl + '/functions/v1/figma-audit-flow', { method: 'POST', headers: { 'Content-Type': 'application/json', 'Authorization': 'Bearer ' + m.accessToken, 'apikey': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhZXlqc3FhbHpjZGVqd3N2b3FsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA2MDYwMDIsImV4cCI6MjA3NjE4MjAwMn0.jThP8cy8deaDkQZlTz6Bb0C1DU6praULawIej2vBghA' }, body: JSON.stringify({ frames: imgs, persona: { name: m.persona.name, description: m.persona.description, painPoints: m.persona.pain_points, goals: m.persona.goals }, auditMode: m.mode }) }); }).then(function(r) { return r.json(); }).then(function(res) { figma.ui.postMessage({ type: 'audit-progress', progress: 100 }); if (res.journeyNarrative) figma.ui.postMessage({ type: 'journey-narrative', narrative: res.journeyNarrative }); figma.ui.postMessage({ type: 'audit-complete', issues: res.issues || [], frameCount: fr.length }); }).catch(function(e) { figma.ui.postMessage({ type: 'audit-error', error: e.message }); }); }
  else if (m.type === 'navigate-to-node') { var n = figma.getNodeById(m.nodeId); if (n) { figma.viewport.scrollAndZoomIntoView([n]); figma.currentPage.selection = [n]; } }
  else if (m.type === 'export-report') figma.ui.postMessage({ type: 'export-ready', format: m.format, content: '# Report\n' + m.data.auditResults.length + ' issues' });
  else if (m.type === 'import-persona' || m.type === 'import-data') { loadFonts().then(function() { var th = THEMES[m.theme] || THEMES.wireframe, w = m.theme === 'wireframe', fr = figma.createFrame(); fr.resize(360, 300); fr.fills = [{ type: 'SOLID', color: th.background }]; fr.strokes = [{ type: 'SOLID', color: th.border }]; fr.strokeWeight = w ? 2 : 1; fr.cornerRadius = w ? 0 : 12; var t = figma.createText(); t.fontName = { family: "Inter", style: "Bold" }; t.characters = m.type === 'import-persona' ? m.data.name : 'Import'; t.fontSize = 18; t.x = 20; t.y = 20; t.fills = [{ type: 'SOLID', color: th.text }]; fr.appendChild(t); figma.viewport.scrollAndZoomIntoView([fr]); figma.notify('✓ Imported!'); figma.ui.postMessage({ type: 'import-success' }); }).catch(function(e) { figma.ui.postMessage({ type: 'import-error', error: e.message }); }); }
  else if (m.type === 'cancel') figma.closePlugin();
};
